import Head from "next/head";
import styles from "../styles/Home.module.css";

import products from "../products.json";
import { fromImageToUrl, APIURL } from "../utils/urls";
import Link from "next/link";

export async function getStaticProps() {
  const productsResponce = await fetch(`${APIURL}/api/products?populate=*`);
  const products = await productsResponce.json();

  // console.log(products);
  return {
    props: {
      products: products,
    },
  };
}

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Udemy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.productAreaWrapper}>
        <h1 className={styles.title}>Next.js Shopping</h1>
        <hr />
        <div className={styles.productArea}>
          {products.data.map((product) => (
            <div key={product.attributes.name} className={styles.product}>
              <Link href={`/product/${product.attributes.slug}`}>
                <a>
                  <div>
                    <div>
                      <img
                        src={fromImageToUrl(
                          product.attributes.image.data.attributes.formats
                            .thumbnail
                        )}
                        alt=""
                        className={styles.productImg}
                      />
                    </div>
                  </div>
                  <div className={styles.productName}>
                    {product.attributes.name} : {product.attributes.price}円
                  </div>
                </a>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
